
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "QwertYYUUII123"
      MSSQL_DB_NAME: "CSV_test2"
      ACCEPT_EULA: "Y"

  # etl_test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #     - 8081:8081
  #   depends_on:
  #     - mssql
  #   environment:
  #     ConnectionStrings__MSSQL_CS: "Server=mssql,1433;Database=CSV_test2;User=sa;Password=QwertYYUUII123;TrustServerCertificate=true;"